name: CI (format & links)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dev tools
        run: |
          npm --yes init -y
          npm i -D prettier

      - name: Prettier check
        run: npx prettier --check "**/*.{html,css,js,json,md,yml,yaml}"

      - name: Internal link check only
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --accept 200,206,429
            --include "**/*.html"
            --include "**/*.md"
            --require-https
            --scheme http
            --base ./
