name: CI (format & links)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install dev tools (pin Prettier)
        run: |
          npm --yes init -y
          npm i -D prettier@3.3.3

      # Note: YAML excluded to avoid noisy failures on workflow files
      - name: Prettier check
        run: npx prettier@3.3.3 --check "**/*.{html,css,js,json,md}"

      - name: Internal link check only (non-blocking)
        uses: lycheeverse/lychee-action@v2
        continue-on-error: true
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,206,429
            --include "**/*.html"
            --include "**/*.md"
            --require-https
            --scheme http
            --base ./
