name: Deploy to FastShoes via FTP

on:
  push:
    branches: [ main ]
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - '**.png'
      - '**.svg'
      - '**.jpg'
      - '**.gif'
      - '!README.md'
      - '!CHANGELOG.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTP (use SFTP if your host supports it)
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL || 'ftp' }}
          local-dir: ./
          server-dir: /jithin/tools/
          # exclude dotfiles/workflows from deploy
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
