name: Deploy to FastShoes via FTP

on:
  workflow_run:
    workflows: ["CI (format & links)"]  # wait for CI to complete
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy via FTP (plain FTP on port 21)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4   # <-- pin exact version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}   # e.g. public_html/jithin/tools
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            README.md
            CHANGELOG.md
            LICENSE
          # dry-run: true
